{
 "title": "Node Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "var_node_list", "label": "Node List", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Records Stored",
   "type": "stat",
   "description": "The number of records stored in each node",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sn_networking_records_stored{node_id=~\"$var_node_list\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sn_networking_process_memory_used_mb{node_id=~\"$var_node_list\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Chunk PUTs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sn_node_put_record_ok_total{node_id=~\"$var_node_list\", record_type=\"Chunk\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Spend PUTs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sn_node_put_record_ok_total{node_id=~\"$var_node_list\", record_type=\"Spend\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Register PUTs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sn_node_put_record_ok_total{node_id=~\"$var_node_list\", record_type=\"Register\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Currently Established Connections",
   "type": "timeseries",
   "description": "The number of connections established by the node at a given moment. \nDialer - the node opened the connection.\nListener - the connection was opened with the node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "libp2p_swarm_connections_established_total{node_id=~\"$var_node_list\"} - sum without(cause) (libp2p_swarm_connections_duration_seconds_count{node_id=~\"$var_node_list\"})",
     "legendFormat": "{{node_id}} {{role}} {{protocols}}"
    }
   ]
  },
  {
   "title": "New connections per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(libp2p_swarm_connections_established_total{node_id=~\"$var_node_list\"}[$__rate_interval])",
     "legendFormat": "{{node_id}} {{role}} {{protocols}}"
    }
   ]
  },
  {
   "title": "Time to establish 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, protocols) (rate(libp2p_swarm_connections_establishment_duration_bucket{node_id=~\"$var_node_list\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Peers in Routing Table",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sn_node_peer_added_to_routing_table_total{node_id=~\"$var_node_list\"} - sn_node_peer_removed_from_routing_table_total{node_id=~\"$var_node_list\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  }
 ]
}